# image name: tespkg/coc-debug-go
FROM tespkg/coc-base

RUN apt-get install -y golang
RUN GO111MODULE=on go get golang.org/x/tools/gopls@latest
ENV PATH=$PATH:/root/go/bin
COPY ./coc-settings.json /root/.config/nvim/coc-settings.json
RUN nvim -u /minimal-coc.nvim -c "CocInstall coc-snippets" -c q
RUN go mod init testcoc
